# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Vegin_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Vegin_iOS
pod 'FSCalendar'
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'

end
